### ISSUE TITLE
Allow length 1 packed 2D arrays

### ISSUE THREAD

**Issue by mbstrange2** [Kuree/kratos#103]
Let's say I have code like 
```python
self._memory_space = self.var("memory_space",  width=desired_width, size=banks_tall, packed=True)
```
If `banks_tall=1`, Kratos currently removes the second dimension which changes the addressing code depending on this variable.  Being able to keep it as a packed struct `logic [0:0][15:0] memory_space` would greatly help with source clarity.

**Comment by Kuree** [comment]
Added in b6dbca2.
