### ISSUE TITLE
Examples segfault

### ISSUE THREAD

**Issue by philipaxer** [Kuree/kratos#151]
Hi,

the uart example segfaults with the latest pip release.

regards
Philip

**Comment by philipaxer** [comment]
That would be nice. I also noticed that the build flow is a bit more complicated than described. 
E.g. you need to have  MAKE_PROGRAM set in your environment.

**Comment by Kuree** [comment]
It is only necessary if you're on Windows. Unfortunately I only have access to Linux machine, so building on Windows or MacOS is difficult for me: I have to trial and error on a CI agent. Based on my limited testing experience, clang+make is the only working combo for me on windows.

Since I don't have much experience with VC++ on Windows, I'd appreciate if you can simplify the building process on Windows.

I should be able to get size parametrization working soon, so I will make a release then. I will let you know once the release is pushed via CI.

**Comment by philipaxer** [comment]
How did you built the previous windows version? I tried mingw64+clang which gave me linker errors then mingw64+g++ which threw again different linker errors.
At this point i gave up.

regards
Philip

**Comment by Kuree** [comment]
The environment setup is [here](https://github.com/Kuree/kratos/blob/master/.appveyor.yml#L25-L28). As you said you need `MAKE_PROGRAM` set. I used the one from msys64 available from appveyor. Then you need to make sure these llvm-related [tools](https://github.com/Kuree/kratos/blob/master/setup.py#L62-L74) are also available.

Also make sure that your Python distribution has the dev files available. I think on Windows they're shipped by default.

I did have some errors with certain cmake, so I pinned it to 3.15.3. This might related to the link error. You can install it locally via pip:
```
python -m pip install wheel cmake==3.15.3
```

**Comment by philipaxer** [comment]
Ok let me retry, but I think its another issue. The python libs and headers are not an issue.
The linker fails here: 
C:\msys32\mingw64\bin\ld: ../src/libkratos.a(util.cc.obj):util.cc:(.text+0xbec): undefined reference to `__imp__dupenv_s'

regards
Philip

**Comment by Kuree** [comment]
This is odd. Windows should have [this function](https://github.com/Kuree/kratos/blob/master/src/util.cc#L479) available, as stated in the [document](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/dupenv-s-wdupenv-s?view=vs-2019).

Are you using vanilia clang or the clang shipped with mingw64? It seems like it is using mingw64's linker, not LLVM's.

**Comment by Kuree** [comment]
Either way I hope to do a release today once I tested the new features more.

**Comment by Kuree** [comment]
New version released. Please let me know if the released version still errors out.
