### ISSUE TITLE
Illegal argument cts to ast.Attribute in ast transformation

### ISSUE THREAD

**Issue by philipaxer** [Kuree/kratos#158]
At the spot where you patch in the call to add_stmt, you are giving a key word argument ``cts`` to ```ast.Attribute```. I guess you wanted to supply ``ctx`` and this is just a typo.

I am surprised that the ast compiler does not complain about the missing ctx.

```
def add_stmt_to_scope(fn_body):
    for i in range(len(fn_body.body)):
        node = fn_body.body[i]
        fn_body.body[i] = ast.Expr(
            value=ast.Call(func=ast.Attribute(value=ast.Name(id="scope", ctx=ast.Load()),  # this is the issue!!!
                                              attr="add_stmt", cts=ast.Load()),
                           args=[node], keywords=[]))
```

**Comment by Kuree** [comment]
Thanks! I'm also surprised that the code still runs. Normally it will error out if missing ctx.
