### ISSUE TITLE
Parameters in arithmetic expressions error with 'unable to fix width'

### ISSUE THREAD

**Issue by philipaxer** [Kuree/kratos#159]
It seems the width of operands is automatically adjusted to match the lhs of the assignment. At least this is my interepretation.

This causes an error if parameters are used in arithmetic expressions. Something like `x = y + PARAM` fails.

regards
Philip

**Comment by Kuree** [comment]
Usually constant values will be resized to match the width of closest operand, if it is safe to do so. I forgot to apply that to parameters. Thanks for catching that.
